import splashTopArrow from "../assests/Images/splashTopArrow/splashTopArrow.png"
import cloudImage from "../assests/Images/cloudImage/cloudImage.png"
import splashLeftArrow from "../assests/Images/splashLeftArrow/splashLeftArrow.png"
import leftCloud from "../assests/Images/leftCloud/leftCloud.png"
import splashLogo from "../assests/Images/splashLogo/splashLogo.png"
import rightArrow from "../assests/Images/rightArrow/rightArrow.png"
import splashBottomCloud from "../assests/Images/splashBottomClou/splashBottomCloud.png"
import bottomArrow from "../assests/Images/bottomArro/bottomArrow.png"
import bottomLeftCloud from "../assests/Images/bottomLeftCloud/bottomLeftCloud.png"
import bottomSplashImage from "../assests/Images/bottomSplashImage/bottomSplashImage.png"
import splashTopImage from "../assests/Images/spalshTopImage/splashTopImage.png"
import spalshBottomImage from "../assests/Images/splashBottomImage/spalshBottomImage.png"
import dubaiImage from "../assests/Images/dubaiImage/dubaiImage.png"
import loginBackArrow from "../assests/Images/loginBackArrow/loginBackArrow.png"
import loginLogoImage from "../assests/Images/loginLogoImage/loginLogoImage.png"
import loginBottomImage from "../assests/Images/loginBottomImage/loginBottomImage.png"
import modalLogo from "../assests/Images/modalLogo/modalLogo.png"
import profileLogo from "../assests/Images/profileLogo/profileLogo.png"
import darwerIcon from "../assests/Images/darwerIcon/darwerIcon.png"
import searchIcon from "../assests/Images/searchIcon/searchIcon.png"
import homeLogo from "../assests/Images/homeLogo/homeLogo.png"
import homeArrow from "../assests/Images/homeArrow/homeArrow.png"
import homeCloud from "../assests/Images/homeCloud/homeCloud.png"
import leftHomeArrow from "../assests/Images/leftHomeArrow/leftHomeArrow.png"
import drawerProfile from "../assests/Images/drawerProfile/drawerProfile.png"
import drawerHome from "../assests/Images/drawerHome/drawerHome.png"



export { splashTopArrow, cloudImage, splashLeftArrow, leftCloud, splashLogo, rightArrow, splashBottomCloud, bottomArrow, bottomLeftCloud, bottomSplashImage, splashTopImage, spalshBottomImage, dubaiImage, loginBackArrow, loginLogoImage, loginBottomImage, modalLogo, profileLogo, darwerIcon, searchIcon,homeLogo,homeArrow,homeCloud,leftHomeArrow,drawerProfile,drawerHome}